// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDePLKpXXXu_MrN_MDmz3j0YCUADxfvzqk',
    appId: '1:427513939451:web:1b9c964c2734335c49b75e',
    messagingSenderId: '427513939451',
    projectId: 'rideal-user',
    authDomain: 'rideal-user.firebaseapp.com',
    storageBucket: 'rideal-user.firebasestorage.app',
    measurementId: 'G-LEGPVZDKKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZLPd8T4J6RBmFIccqCYMxedNxdN2ERGw',
    appId: '1:235222897305:android:79062f633ed4bdd7709e08',
    messagingSenderId: '235222897305',
    projectId: 'rideal-426b8',
    storageBucket: 'rideal-426b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJIUWJPL73hsXYy3IpKsQI97riF4MC8yM',
    appId: '1:235222897305:ios:844eb997be5acc49709e08',
    messagingSenderId: '235222897305',
    projectId: 'rideal-426b8',
    storageBucket: 'rideal-426b8.firebasestorage.app',
    iosBundleId: 'com.rds.ridealdriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0_7GepdZJdupfMOIqX_rb9T-rFZdigx0',
    appId: '1:427513939451:ios:8a87e77c7f1da3ad49b75e',
    messagingSenderId: '427513939451',
    projectId: 'rideal-user',
    storageBucket: 'rideal-user.firebasestorage.app',
    iosBundleId: 'com.rds.ridealdriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDePLKpXXXu_MrN_MDmz3j0YCUADxfvzqk',
    appId: '1:427513939451:web:1d3e76783535171049b75e',
    messagingSenderId: '427513939451',
    projectId: 'rideal-user',
    authDomain: 'rideal-user.firebaseapp.com',
    storageBucket: 'rideal-user.firebasestorage.app',
    measurementId: 'G-7HZSS078DQ',
  );
}